"""add_credentials_trust_infrastructure

Revision ID: 31f43d148703
Revises: 9bb47ac3c11c
Create Date: 2026-01-14 14:11:21.921360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f43d148703'
down_revision = '9bb47ac3c11c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EDUCATION', 'EMPLOYMENT', 'SKILL', 'CERTIFICATION', 'STARTUP_ROLE', name='credentialtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('USER_INPUT', 'SYSTEM_GENERATED', 'THIRD_PARTY', name='credentialsource'), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'SUBMITTED', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_created_at'), 'credentials', ['created_at'], unique=False)
    op.create_index(op.f('ix_credentials_type'), 'credentials', ['type'], unique=False)
    op.create_index(op.f('ix_credentials_user_id'), 'credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix_credentials_verification_status'), 'credentials', ['verification_status'], unique=False)
    op.create_table('credential_hashes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=True),
    sa.Column('tx_signature', sa.String(length=88), nullable=True),
    sa.Column('block_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_hashes_credential_id'), 'credential_hashes', ['credential_id'], unique=False)
    op.create_index(op.f('ix_credential_hashes_hash'), 'credential_hashes', ['hash'], unique=False)
    op.create_table('trust_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=True),
    sa.Column('signal_type', sa.Enum('VERIFIED_DEGREE', 'VERIFIED_EMPLOYMENT', 'FOUNDER_VERIFIED', 'INVESTOR_ACTIVITY', 'STARTUP_ROLE_VERIFIED', name='trustsignaltype'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_signals_created_at'), 'trust_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_trust_signals_credential_id'), 'trust_signals', ['credential_id'], unique=False)
    op.create_index(op.f('ix_trust_signals_signal_type'), 'trust_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_trust_signals_user_id'), 'trust_signals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trust_signals_user_id'), table_name='trust_signals')
    op.drop_index(op.f('ix_trust_signals_signal_type'), table_name='trust_signals')
    op.drop_index(op.f('ix_trust_signals_credential_id'), table_name='trust_signals')
    op.drop_index(op.f('ix_trust_signals_created_at'), table_name='trust_signals')
    op.drop_table('trust_signals')
    op.drop_index(op.f('ix_credential_hashes_hash'), table_name='credential_hashes')
    op.drop_index(op.f('ix_credential_hashes_credential_id'), table_name='credential_hashes')
    op.drop_table('credential_hashes')
    op.drop_index(op.f('ix_credentials_verification_status'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_user_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_type'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_created_at'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###

